/*
 * 検索条件を復元してから検索を行う秀丸マクロ
 * （カーソル位置の単語をハイライト表示する秀丸マクロの付属マクロ）
 *
 * Ver.1.1 (2013-12-21)
 *
 * Yasunori Miyamoto
 * http://tipszone.jp/20121003_hidemaru-config/
 * mailto: nori@tipszone.jp
 */

// 検索条件を復元
$$ini_file = currentmacrodirectory + "\\highlight.ini";
##search_option = getininum($$ini_file, getenv("UserName"), "search_option");
if (##search_option != 0) {
	setsearch "", ##search_option;
	writeininum $$ini_file, getenv("UserName"), "search_option", 0;
}

find;
